CarWash/Models/Car.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CarWash.Models
{
    public class Car
    {      
        public int Id { get; set;}

        [Display(Name = "Plate Number")]
        [Required]
        [MaxLength(50, ErrorMessage = ("Name cannot exceed 50 characters"))]
        public string CarNo { get; set; }

        public string CarColor { get; set; }
        public string CarType { get; set; }
        public string UserId { get; set; }
        public User User { get; set; }
        public IList<UserCar> UserCar { get; set; }
        public ICollection<Reservation> Reservation { get; set; }

       
       





    }
}

CarWash/Controllers/AfterloginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using CarWash.Data;
using CarWash.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CarWash.Controllers
{
    public class AfterloginController : Controller
    {
        private readonly CarWashContext _context;

        private object _httpContextAccessor;
       

        public AfterloginController(CarWashContext context)
        {
            _context = context;
           
        }

        public IActionResult Afterloginhome()
        {
            return View();
        }

        public async Task<IActionResult> Index()
        {
           
            return View(await _context.User.ToListAsync());
        }

        // GET: Cars/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Cars/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Types/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,Name,CarNo,CarType,Colour")] User user)
        {
            
            if (id != user.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        private bool UserExists(string id)
        {
            return _context.User.Any(e => e.Id == id);
        }


        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Cars/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var user = await _context.User.FindAsync(id);
            _context.User.Remove(user);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Payment(string searchString)
        {
            var reservation = from m in _context.Reservation
                              select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                reservation = reservation.Where(s => s.Address.Contains(searchString));
            }

            return View(await reservation.ToListAsync());
        }
        
    }
}

CarWash/Controllers/ReservationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using CarWash.Data;
using CarWash.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace CarWash.Controllers
{
    [Authorize]
    public class ReservationsController : Controller
    {
        private readonly CarWashContext _context;

        private object _httpContextAccessor;

        public ReservationsController(CarWashContext context)
        {
            _context = context;
        }
        
        //public async Task<IActionResult> Index(string id)
        //{
        //    var reservation = from m in _context.Reservation
        //                      select m;

        //    if (!String.IsNullOrEmpty(id))
        //    {
        //        reservation = reservation.Where(s => s.Address.Contains(id));
        //    }

        //    return View(await _context.Reservation.ToListAsync());
        //}
        //forstaff
        public async Task<IActionResult> Index()
        {

            var userId = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);

            var reservation = _context.Reservation
                .Include(r => r.Car)
                 .ThenInclude(s => s.User)
                .Include(r => r.Types)
                .Where(x => x.Car.UserId == userId)
                .ToList();



            return View(await _context.Reservation.Where(x => x.Car.UserId == userId).ToListAsync());
        }



        public string DateSort { get; set; }
        //Ni list semua reservation untuk admin
        [Authorize]
        [HttpGet]
        public async Task<IActionResult> GetReservation(int id, string sortOrder)
        {

            var userId = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
            ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";
            ViewData["IdSortParm"] = String.IsNullOrEmpty(sortOrder) ? "id_decs" : "";
            var reservation = _context.Reservation
                .Include(r => r.Car)
                .Include(r => r.Types)
                .FirstOrDefault();
            var reserve = _context.Reservation.AsQueryable();

            switch (sortOrder)
            {

                case "Date":
                    reserve = reserve.OrderByDescending(s => s.Date);
                    break;
                default:
                    reserve = reserve.OrderBy(s => s.Id);
                    break;
            }
                    return View(await _context.Reservation.OrderByDescending(x => x.Date).ToListAsync());
        }

        //[Route("reservations/create/car/{carid}")]
        public IActionResult Create(int carid)
        {
            ViewBag.CarId = carid;
            return View();
        }

        //[Route("reservations/create/car/{carid}")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Reservation reservationModel)
        {
            if (ModelState.IsValid)
            {

                var userId = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
                var car = _context.Car.Where(x => x.Id == reservationModel.CarId).FirstOrDefault();
                var type = _context.Types.Where(x => x.Id == reservationModel.TypesId).FirstOrDefault();
                double Prices = type.Prices;
                string CarType = car.CarType;
                int TypeId = type.Id;
                double Amount = reservationModel.Amount;

                if(CarType == "Sedan")
                {
                   if(TypeId == 22)
                    {
                        Amount += Prices;
                        if (reservationModel.Vacuum)
                        {
                            Amount += Prices + 2;
                        }

                        else if (reservationModel.Polish)
                        {
                            Amount += Prices + 5;
                        }
                        else if (reservationModel.Amortires)
                        {
                            Amount += Prices + 2;
                        }
                        else if (reservationModel.Freshner)
                        {
                            Amount += Prices + 2;
                        }
                    }
                    else if (TypeId == 23)
                    {
                        Amount += Prices;
                        if (reservationModel.Leatherconditioner)
                        {
                            Amount += Prices + 4;
                        }

                        else if (reservationModel.Polish)
                        {
                            Amount += Prices + 5;
                        }
                        else if (reservationModel.Enginewash)
                        {
                            Amount += Prices + 5;
                        }
                        else if (reservationModel.Freshner)
                        {
                            Amount += Prices + 2;
                        }
                    }

                    else 
                    {
                        Amount += Prices;
                        if (reservationModel.Leatherconditioner)
                        {
                            Amount += Prices + 4;
                        }

                        else if (reservationModel.Polish)
                        {
                            Amount += Prices + 5;
                        }
                         else if (reservationModel.Freshner)
                        {
                            Amount += Prices + 2;
                        }
                    }
                }

                else if (CarType == "MPV")
                {
                   
                    if (TypeId == 22)
                    {
                        Amount += Prices+2 ;
                        if (reservationModel.Vacuum)
                        {
                            Amount += Prices + 2;
                        }

                        else if (reservationModel.Polish)
                        {
                            Amount += Prices + 5;
                        }
                        else if (reservationModel.Amortires)
                        {
                            Amount += Prices + 3;
                        }
                        else if (reservationModel.Freshner)
                        {
                            Amount += Prices + 2;
                        }
                    }
                    else if (TypeId == 23)
                    {
                       
                        Amount += Prices+3;
                        if (reservationModel.Leatherconditioner)
                        {
                            Amount += Prices + 4;
                        }

                        else if (reservationModel.Polish)
                        {
                            Amount += Prices + 5;
                        }
                        else if (reservationModel.Enginewash)
                        {
                            Amount += Prices + 5;
                        }
                        else if (reservationModel.Freshner)
                        {
                            Amount += Prices + 2;
                        }
                    }

                    else
                    {

                        Amount += Prices+1;
                        if (reservationModel.Leatherconditioner)
                        {
                            Amount += Prices + 4;
                        }

                        else if (reservationModel.Polish)
                        {
                            Amount += Prices + 5;
                        }
                        else if (reservationModel.Freshner)
                        {
                            Amount += Prices + 2;
                        }
                    }
                }

                else if (CarType == "SUV")
                {
                   
                    if (TypeId == 22)
                    {
                        Amount += Prices+4;
                        if (reservationModel.Vacuum)
                        {
                            Amount += Prices + 4;
                        }

                        else if (reservationModel.Polish)
                        {
                            Amount += Prices + 8;
                        }
                        else if (reservationModel.Amortires)
                        {
                            Amount += Prices + 2;
                        }
                        else if (reservationModel.Freshner)
                        {
                            Amount += Prices + 2;
                        }
                    }
                    else if (TypeId == 23)
                    {

                        Amount += Prices+5;
                        if (reservationModel.Leatherconditioner)
                        {
                            Amount += Prices + 5;
                        }

                        else if (reservationModel.Polish)
                        {
                            Amount += Prices + 8;
                        }
                        else if (reservationModel.Enginewash)
                        {
                            Amount += Prices + 5;
                        }
                        else if (reservationModel.Freshner)
                        {
                            Amount += Prices + 2;
                        }
                    }

                    else
                    {

                        Amount += Prices+5;
                        if (reservationModel.Leatherconditioner)
                        {

CarWash/Views/Cars/Create.cshtml
@model CarWash.Models.Car

@{
    ViewData["Title"] = "Create";
}

<h1 style="font-family:'Courier New'" class="font-weight-bold">Register your Car</h1>

<section class="view intro-2">

    <div class="mask rgba-stylish-strong h-100 d-flex justify-content-center align-items-center">
        <div class="container">
            <div class="row">
                <div class="col-xl-5 col-lg-6 col-md-10 col-sm-12 mx-auto mt-lg-5">

                    <!--Form with header-->
                    <div class="text-center">
                        @*<h1 class="display-4 font-weight-bold mb-5 wow fadeInUp"> Wash-It!</h1>*@
                    </div>
                    <div class="card wow fadeIn" data-wow-delay="0.3s">
                        <div class="card-body">

                            <!--Header-->
                            <div class="form-header purple-gradient">
                                
                            </div>
                            <form asp-action="Create">
                                <!--Body-->

                                <div class="md-form">
                                    <label asp-for="CarNo" class="control-label"></label>
                                    <input asp-for="CarNo" class="form-control" />
                                    <span asp-validation-for="CarNo" class="text-danger"></span>
                                </div>

                                <div class="md-form">
                                    <label asp-for="CarColor" class="control-label"></label>
                                    <select asp-for="CarColor" class="form-control">
                                        <option value="Black">Black</option>
                                        <option value="White">White</option>
                                        <option value="Red">Red</option>
                                        <option value="Green">Green</option>
                                        <option value="Yellow">Yellow</option>
                                        <option value="Silver">Silver</option>
                                        <option value="Blue">Blue</option>
                                        <option value="Others">Others</option>
                                    </select>
                                    <span asp-validation-for="CarColor" class="text-danger"></span>
                                </div>
                                <div class="md-form">
                                    <label asp-for="CarType" class="control-label"></label>
                                    <select asp-for="CarType" class="form-control">
                                        <option value="Sedan">Sedan</option>
                                        <option value="MPV">MPV</option>
                                        <option value="SUV">SUV</option>
                                        <option value="Hatchback">Hatchback</option>
                                        <option value="Convertible">Convertible</option>
                                    </select>
                                    <span asp-validation-for="CarType" class="text-danger"></span>
                                </div>
                                <br />
                                <div class="form-group form-check">
                                    <input type="submit" value="Register" class="btn btn-primary" />
                                    <a asp-action="Index" class="btn btn-primary">List of Car</a>
                                </div>
 
                            </form>
                        </div>
                    </div>

                    <!--/Form with header-->

                </div>
            </div>
        </div>
    </div>
</section>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CarWash/Views/Cars/Delete.cshtml
@model CarWash.Models.Car

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Car</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CarNo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CarNo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CarColor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CarColor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CarType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CarType)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CarWash/Views/Cars/Details.cshtml
@model CarWash.Models.Car

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div >
    <h4>Car</h4>
    <hr />
    
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.CarNo)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.CarNo)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.CarColor)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.CarColor)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.CarType)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.CarType)
            </dd>
        </dl>
   
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CarWash/Views/Cars/Edit.cshtml
@model CarWash.Models.Car

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Car</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="CarNo" class="control-label"></label>
                <input asp-for="CarNo" class="form-control" />
                <span asp-validation-for="CarNo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CarColor" class="control-label"></label>
                <input asp-for="CarColor" class="form-control" />
                <span asp-validation-for="CarColor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CarType" class="control-label"></label>
                <input asp-for="CarType" class="form-control" />
                <span asp-validation-for="CarType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />

            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CarWash/Views/Cars/Index.cshtml
@model IEnumerable<CarWash.Models.Car>

@{
    ViewData["Title"] = "Index";
}
<br />

    <h1 style="font-family:'Courier New'" class="font-weight-bold">Choose your Car</h1>



    <a class="btn btn-outline-dark " asp-action="Create" >Create New</a>


<table class="table">
    @*<thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.CarNo)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CarColor)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CarType)
                </th>
                <th></th>
            </tr>
        </thead>*@
    <div class="card-deck">
        @foreach (var item in Model)
        {
        <div class="col col-lg-3">
            <div class="card m-3">
                <div class="card-header">
                    <a asp-controller="Reservations" asp-action="Create" asp-route-carid="@item.Id" class="btn btn-rounded btn-outline-white">@Html.DisplayFor(modelItem => item.CarNo)</a>
                </div>
                <img class="card-img-top" src="~/images/car.png" />
                <div class="card-body text-center">
                    <p> @Html.DisplayFor(modelItem => item.CarType)</p>
                    <hr>
                    <p> @Html.DisplayFor(modelItem => item.CarColor)</p>
                </div>
                <div class="card-footer text-center">
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </div>
            </div>
        </div>
        }
    </div>
</table>

CarWash/Views/Cars/Staffindex.cshtml
@model IEnumerable<CarWash.Models.Car>

@{
    ViewData["Title"] = "Index";
}

<h1 style="font-family:'Courier New'" class="font-weight-bold">Choose your Car</h1>


<div class="btn btn-outline-primary sticky-top">
    <a asp-action="Create">Create New</a>
</div>

<table class="table">
    @*<thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.CarNo)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CarColor)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CarType)
                </th>
                <th></th>
            </tr>
        </thead>*@
    <div class="card-deck">
        @foreach (var item in Model)
        {
        <div class="col col-lg-3">
            <div class="card m-3">
                <div class="card-header">
                    <a asp-controller="Reservations" asp-action="Create" asp-route-carid="@item.Id" class="btn btn-rounded btn-outline-white">@Html.DisplayFor(modelItem => item.CarNo)</a>
                </div>
                <img class="card-img-top" src="~/images/car.png" />
                <div class="card-body text-center">
                    <p> @Html.DisplayFor(modelItem => item.CarType)</p>
                    <hr>
                    <p> @Html.DisplayFor(modelItem => item.CarColor)</p>
                </div>
                <div class="card-footer text-center">
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </div>
            </div>
        </div>
                }
            </div>
            
</table>

CarWash/Views/Cars/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CarWash</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    @*<link rel="stylesheet" href="~/css/site.css" />*@
    <link rel="stylesheet" type="text/css" href="~/css/car.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-dark" style="background-color:#0d47a1;">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Afterlogin" asp-action="Afterloginhome">Wash-It!</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    @*<partial name="_LoginPartial" />*@
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Afterlogin" asp-action="Afterloginhome">Home</a>
                        </li>



                    </ul>
                </div>
            </div>
        </nav>
    </header>


    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <div class="pt-lg-5">
        <footer class="border-top footer text-muted fixed-bottom">
            <div class="container">
                &copy; 2020 - CarWash - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
    </div>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @RenderSection("Scripts", required: false)
</body>
</html>