CarWash/Controllers/AfterloginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using CarWash.Data;
using CarWash.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CarWash.Controllers
{
    public class AfterloginController : Controller
    {
        private readonly CarWashContext _context;

        private object _httpContextAccessor;
       

        public AfterloginController(CarWashContext context)
        {
            _context = context;
           
        }

        public IActionResult Afterloginhome()
        {
            return View();
        }

        public async Task<IActionResult> Index()
        {
           
            return View(await _context.User.ToListAsync());
        }

        // GET: Cars/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Cars/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Types/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,Name,CarNo,CarType,Colour")] User user)
        {
            
            if (id != user.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        private bool UserExists(string id)
        {
            return _context.User.Any(e => e.Id == id);
        }


        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Cars/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var user = await _context.User.FindAsync(id);
            _context.User.Remove(user);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Payment(string searchString)
        {
            var reservation = from m in _context.Reservation
                              select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                reservation = reservation.Where(s => s.Address.Contains(searchString));
            }

            return View(await reservation.ToListAsync());
        }
        
    }
}

CarWash/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CarWash.Data;
using CarWash.Models;
using System.Security.Claims;

namespace CarWash.Controllers
{
    public class CarsController : Controller
    {
        private readonly CarWashContext _context;

        public CarsController(CarWashContext context)
        {
            _context = context;
        }

        // GET: Cars
        public async Task<IActionResult> Index()
        {
            var userId = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
            return View(await _context.Car.Where(x=>x.UserId==userId).ToListAsync());
        }

        //staffaccess
        public async Task<IActionResult> Staffindex()
        {
            var userId = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
            return View(await _context.Car.ToListAsync());
        }


        // GET: Cars/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _context.Car
                .FirstOrDefaultAsync(m => m.Id == id);
            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        // GET: Cars/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Cars/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( Car carModel)
        {
            if (ModelState.IsValid)
            {
                var userId = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);

                var car = new Car();
                {
                    car.Id = carModel.Id;
                    car.CarColor = carModel.CarColor;
                    car.CarNo = carModel.CarNo;
                    car.CarType = carModel.CarType;
                    car.UserId = userId;

                }

                _context.Add(car);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(ReservationsController.Create), "Reservations", new { carid = car.Id });
            }
            return View(carModel);
        }

        // GET: Cars/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _context.Car.FindAsync(id);
            if (car == null)
            {
                return NotFound();
            }
            return View(car);
        }

        // POST: Cars/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CarId,CarNo,CarColor,CarType")] Car car)
        {
            if (id != car.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(car);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CarExists(car.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(car);
        }

        // GET: Cars/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _context.Car
                .FirstOrDefaultAsync(m => m.Id == id);
            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        // POST: Cars/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var car = await _context.Car.FindAsync(id);
            _context.Car.Remove(car);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CarExists(int id)
        {
            return _context.Car.Any(e => e.Id == id);
        }
    }
}

CarWash/Views/Afterlogin/Afterloginhome.cshtml
@model CarWash.Models.UserRegistrationModel

<style>

    body {
        background-color: white;
        color: black;
    }

    .footer {
        padding: 1em;
        color: white;
        background-color: black;
        clear: left;
        text-align: center;
    }

    .card {
        margin: 1rem auto;
        position: relative;
    }

    .card-body {
        z-index: 2;
        position: absolute;
        right: 0;
        bottom: 0;
        left: 0;
    }
    .img {
        max-width: 300px;
        max-height: 300px;
    }
</style>


@if (User.IsInRole("Administrator"))
{
    <div class="container-fluid text-center">
        <h2></h2>
        <br>
        <div class="row">
            <!-- Card -->
            <div class="card" style="max-width: 20rem;">
                <a asp-controller="Reservations" asp-action="GetReservation">
                    <!-- Card image -->
                    <img class="card-img-top" src="https://mdbootstrap.com/img/Mockups/Lightbox/Thumbnail/img%20(67).jpg" alt="Card image cap">

                    <!-- Card content -->
                    <div class="card-body text-dark rgba-black-light p-2">

                        <span class="glyphicon glyphicon-off"></span>
                        <b>Reservations</b>

                    </div>
                </a>
            </div>
            <!-- Card -->
            <!-- Card -->
            <div class="card" style="max-width: 20rem;">
                <a asp-controller="Users" asp-action="Viewstaff">
                    <!-- Card image -->
                    <img class="card-img-top" src="https://mdbootstrap.com/img/Mockups/Lightbox/Thumbnail/img%20(67).jpg" alt="Card image cap">

                    <!-- Card content -->
                    <div class="card-body text-dark rgba-black-light p-2">

                        <span class="glyphicon glyphicon-off"></span>
                        <b>Staff</b>

                    </div>
                </a>
            </div>
            <!-- Card -->
            <!-- Card -->
            <div class="card" style="max-width: 20rem;">
                <a asp-controller="Users" asp-action="Customer">
                    <!-- Card image -->
                    <img class="card-img-top" src="https://mdbootstrap.com/img/Mockups/Lightbox/Thumbnail/img%20(67).jpg" alt="Card image cap">

                    <!-- Card content -->
                    <div class="card-body text-dark rgba-black-light p-2">

                        <span class="glyphicon glyphicon-off"></span>
                        <b>Customer</b>

                    </div>
                </a>
            </div>
            <!-- Card -->
        </div>
        <div class="row">
            <!-- Card -->
            <div class="card" style="max-width: 20rem;">
                <a asp-controller="Cars" asp-action="Staffindex">
                    <!-- Card image -->
                    <img class="card-img-top" src="https://mdbootstrap.com/img/Mockups/Lightbox/Thumbnail/img%20(67).jpg" alt="Card image cap">

                    <!-- Card content -->
                    <div class="card-body text-dark rgba-black-light p-2">

                        <span class="glyphicon glyphicon-off"></span>
                        <b>Car</b>

                    </div>
                </a>
            </div>
            <!-- Card -->
            <!-- Card -->
            <div class="card" style="max-width: 20rem;">
                <a asp-controller="Types" asp-action="Index">
                    <!-- Card image -->
                    <img class="card-img-top" src="https://mdbootstrap.com/img/Mockups/Lightbox/Thumbnail/img%20(67).jpg" alt="Card image cap">

                    <!-- Card content -->
                    <div class="card-body text-dark rgba-black-light p-2">

                        <span class="glyphicon glyphicon-off"></span>
                        <b>Types</b>

                    </div>
                </a>
            </div>
            <!-- Card -->
        </div>
        <br><br>
    </div>

}
else if (User.IsInRole("Staff"))
{
    <div class="container-fluid text-center">
        <h2></h2>
        <br>
        <div class="row">
            <!-- Card -->
            <div class="card" style="max-width: 20rem;">
                <a asp-controller="Reservations" asp-action="GetReservation">
                    <!-- Card image -->
                    <img class="card-img-top" src="https://mdbootstrap.com/img/Mockups/Lightbox/Thumbnail/img%20(67).jpg" alt="Card image cap">

                    <!-- Card content -->
                    <div class="card-body text-dark rgba-black-light p-2">

                        <span class="glyphicon glyphicon-off"></span>
                        <b>Reservations</b>

                    </div>
                </a>
            </div>
            <!-- Card -->
            <!-- Card -->
            <div class="card" style="max-width: 20rem;">
                <a asp-controller="Locations" asp-action="Index">
                    <!-- Card image -->
                    <img class="card-img-top" src="https://mdbootstrap.com/img/Mockups/Lightbox/Thumbnail/img%20(67).jpg" alt="Card image cap">

                    <!-- Card content -->
                    <div class="card-body text-dark rgba-black-light p-2">

                        <span class="glyphicon glyphicon-off"></span>
                        <b>Location History</b>

                    </div>
                </a>
            </div>
            <!-- Card -->

        </div>
        <br><br>
    </div>


}
else
{
    <!-- Main navigation -->
    <!-- Full Page Intro -->
    <div id="intro-section" class="view">

        <!-- Mask & flexbox options-->
        <!--Grid column-->
        <div class="col-md-12 mb-4 white-text text-center wow fadeIn">
            <div class="container-fluid text-center">
                <h2></h2>
                <br>
                <a asp-controller="Cars" asp-action="Index" class="btn btn-rounded btn-outline-white">
                    <img src="~/images/logo.png" /><br />
                    <i class="fa fa-home btn btn-info"></i> Book Now!
                </a><br><br>
            </div>
        </div>
        <!--Grid column-->
    </div>
    
    <!--Grid row-->
<div class="container-fluid text-center py-5" style=" background-color:#0d47a1;">
    <div class="row">
        <!-- Container -->
        <div class="col">

            <!-- Section heading -->
            <h2 class="h1-responsive font-weight-bold mb-5 text-white">Our Services</h2>
            <!-- Section description -->
            <p class="grey-text w-responsive mx-auto mb-5 text-white">
                We provide vary type of services that our customer can choose with a reasonable price. You just need to stay where you are and we will entertain you by going to you place. Worry no more about no time to wash your car!
            </p>

            <!-- Grid row -->
            <div class="row text-center">

                <!-- Grid column -->
                <div class="col-lg-4 col-md-12 mb-lg-0 mb-4">
                    <!--Featured image-->
                    <div class="view overlay rounded z-depth-1">
                        <img src="~/images/IndexCar/wash.jpg" class="img-fluid" alt="Sample project image">
                        <a>
                            <div class="mask rgba-white-slight"></div>
                        </a>
                    </div>
                    <!--Excerpt-->
                    <div class="card-body pb-0">
                        <h4 class="font-weight-bold my-3 text-white">Basic Services</h4>
                        <p class=" text-white">
                            Your car will be wash within 30 minutes depends on the services you chose.
                        </p>

                    </div>
                </div>
                <!-- Grid column -->
                <!-- Grid column -->
                <div class="col-lg-4 col-md-6 mb-md-0 mb-4">
                    <!--Featured image-->
                    <div class="view overlay rounded z-depth-1">
                        <img src="~/images/IndexCar/vacuum.jpg" class="img-fluid" alt="Sample project image">
                        <a>
                            <div class="mask rgba-white-slight"></div>
                        </a>
                    </div>
                    <!--Excerpt-->
                    <div class="card-body pb-0">
                        <h4 class="font-weight-bold my-3 text-white">Add-On</h4>
                        <p class="text-white">
                            They are varies extra services that customer can choose.
                        </p>

                    </div>
                </div>
                <!-- Grid column -->
                <!-- Grid column -->
                <div class="col-lg-4 col-md-6">
                    <!--Featured image-->
                    <div class="view overlay rounded z-depth-1">
                        <img src="~/images/IndexCar/polish.jpg" class="img-fluid" alt="Sample project image">
                        <a>
                            <div class="mask rgba-white-slight"></div>
                        </a>
                    </div>
                    <!--Excerpt-->
                    <div class="card-body pb-0">
                        <h4 class="font-weight-bold my-3 text-white">Flexible</h4>
                        <p class="text-white">
                            You can choose time and date when you would like to have the service.
                        </p>

                    </div>
                </div>
                <!-- Grid column -->

            </div>
            <!-- Grid row -->

        </div>
        <!-- Container -->
    </div>
</div>

<div class="container-fluid pt-5 pb-4">
    <div class="row">
        <div class="col-md-4 ">
            <img class="img" src="~/images/NewFolder/earth.png" />
        </div>
        <div class="col-sm-8">
            <h4><strong>MISSION</strong></h4> To be there for you<br /><br />
            <h4><strong>VISSION</strong></h4> To fullfill all your request
        </div>
    </div>
</div>

}

CarWash/Views/Afterlogin/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CarWash</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    @*<link rel="stylesheet" href="~/css/site.css" />*@
    <link rel="stylesheet" type="text/css" href="~/css/aftrlgn.css">
</head>
<style>
     .jumbotron {
            text-align: center;
            background-size: cover;
            padding-top: 15%;
            padding-bottom: 15%;
            background-color:#0d47a1;
            font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif
    }
</style>
<body>
    <header>
        @*<nav class="navbar navbar-expand-sm navbar-light fixed-top" style="background-color:#0d47a1;">
                <div class="container">
                    <a class="navbar-brand text-light" asp-area="" asp-controller="Afterlogin" asp-action="Afterloginhome">Home</a>
                    <div class="dropdown">
                        <a class="nav-link text-light dropdown-toggle" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            More
                        </a>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                            <a class="dropdown-item" asp-controller="Reservations" asp-action="Index">History</a>
                            <a class="dropdown-item" asp-controller="Cars" asp-action="Index">Car</a>
                            <a class="dropdown-item" asp-controller="Users" asp-action="About">About</a>
                        </div>
                    </div>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
                            aria-controls="navbarSupportedContent-7" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <partial name="_LoginPartial" />
                    </div>
                </div>
            </nav>*@
        @if (User.IsInRole("Visitor"))
        {<nav class="navbar navbar-expand-sm navbar-light fixed-top" style="background-color:#0d47a1;">
                <div class="container">
                    <a class="navbar-brand text-light" asp-area="" asp-controller="Afterlogin" asp-action="Afterloginhome">Home</a>
                    <div class="dropdown">
                        <a class="nav-link text-light dropdown-toggle" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            More
                        </a>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                            <a class="dropdown-item" asp-controller="Reservations" asp-action="Index">History</a>
                            <a class="dropdown-item" asp-controller="Cars" asp-action="Index">Car</a>
                            <a class="dropdown-item" asp-controller="Users" asp-action="About">About</a>
                        </div>
                    </div>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
                            aria-controls="navbarSupportedContent-7" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <partial name="_LoginPartial" />
                    </div>
                </div>
            </nav>
            <div class="jumbotron jumbotron-fluid ">
                <div class="container h-50 ">
                    <h1 class="display-3 text-white">Welcome to Wash-It</h1>
                    <h4 class="lead">Make your car shine</h4>

                </div>
            </div>

            <!-- Jumbotron -->
        }
        else if (User.IsInRole("Staff"))
        { <nav class="navbar navbar-expand-sm navbar-light fixed-top" style="background-color:#0d47a1;">
                <div class="container">
                    <a class="navbar-brand text-light" asp-area="" asp-controller="Afterlogin" asp-action="Afterloginhome">Home</a>

                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
                            aria-controls="navbarSupportedContent-7" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <partial name="_LoginPartial" />
                    </div>
                </div>
            </nav>
            <div class="container  pt-4">
                <div class="pt-5 pb-3 text-center">
                    <h3><b><p>Welcome, Staff!</p></b></h3>
                </div>
            </div>
        }

        else
        { <nav class="navbar navbar-expand-sm navbar-light fixed-top" style="background-color:#0d47a1;">
                <div class="container">
                    <a class="navbar-brand text-light" asp-area="" asp-controller="Afterlogin" asp-action="Afterloginhome">Home</a>

                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
                            aria-controls="navbarSupportedContent-7" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <partial name="_LoginPartial" />
                    </div>
                </div>
            </nav>
            <div class="container  pt-4">
                <div class="pt-5 pb-3 text-center">
                    <h3><b><p>Welcome, Admin!</p></b></h3>
                </div>
            </div>
        }
    </header>


    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    @if (User.IsInRole("Visitor"))
    {
        <div class="pt-lg-5">
            <footer class="border-top footer text-muted ">
                <div class="container">
                    &copy; 2020 - CarWash - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </div>
            </footer>
        </div>
    }
    else
    {
        <div class="pt-lg-5">
            <footer class="border-top footer text-muted fixed-bottom">
                <div class="container">
                    &copy; 2020 - CarWash - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </div>
            </footer>
        </div>
    }
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>